[window]
opacity = 0.90

[font]
size = 8 

[font.normal]
family = "Comic Mono" # Linux/BSD
style = "Regular"

[font.italic]
family = "Comic Mono" # Linux/BSD
style = "Regular"

[colors]
primary.background = "#000000" #"#062329"
primary.foreground = "#ffffff" #"#062329"

[colors.normal]
red = "#ff0000"
green = "#00ff00"
blue = "#0000ff"

[colors.bright]
red = "#ff0000"
green = "#00ff00"
blue = "#0000ff"
