[font]
size = 8 

[font.normal]
family = "Ubuntu Mono" # Linux/BSD
style = "Regular"

[font.italic]
family = "Ubuntu Mono" # Linux/BSD
style = "Regular"

[colors]
primary.background = "#181818" #"#062329"

[colors.normal]
red = "#ff0000"
green = "#00ff00"
#blue = "#0000ff"
magenta = "#6a0dad"

[colors.bright]
red = "#ff0000"
green = "#00ff00"
#blue = "#0000ff"
magenta = "#6a0dad"
